"""Configuration constants for the portfolio optimizer."""

RISK_FREE_RATE = 0.05
DEFAULT_HISTORY_PERIOD = "2y"
TRADING_DAYS_PER_YEAR = 252
BENCHMARK_TICKER = "SPY"

RISK_PROFILES = {
    "bajo": {"target_volatility": 0.10, "label": "Conservative"},
    "medio": {"target_volatility": 0.18, "label": "Balanced"},
    "alto": {"target_volatility": 0.30, "label": "Aggressive"},
}

# Curated list of S&P 500 stocks (ticker -> display name)
SP500_TICKERS = {
    # Technology
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corp.",
    "GOOGL": "Alphabet Inc. (Google)",
    "META": "Meta Platforms Inc.",
    "NVDA": "NVIDIA Corp.",
    "AVGO": "Broadcom Inc.",
    "ADBE": "Adobe Inc.",
    "CRM": "Salesforce Inc.",
    "INTC": "Intel Corp.",
    "AMD": "Advanced Micro Devices",
    "ORCL": "Oracle Corp.",
    "ACN": "Accenture plc",
    "NOW": "ServiceNow Inc.",
    "CSCO": "Cisco Systems",
    "IBM": "IBM Corp.",
    "TXN": "Texas Instruments",
    "QCOM": "Qualcomm Inc.",
    "AMAT": "Applied Materials",
    "MU": "Micron Technology",
    "PANW": "Palo Alto Networks",
    "SNPS": "Synopsys Inc.",
    "CDNS": "Cadence Design Systems",
    "CRWD": "CrowdStrike Holdings",
    "MRVL": "Marvell Technology",
    # Consumer / E-commerce
    "AMZN": "Amazon.com Inc.",
    "TSLA": "Tesla Inc.",
    "HD": "Home Depot Inc.",
    "LOW": "Lowe's Companies",
    "MCD": "McDonald's Corp.",
    "SBUX": "Starbucks Corp.",
    "NKE": "Nike Inc.",
    "WMT": "Walmart Inc.",
    "COST": "Costco Wholesale",
    "PG": "Procter & Gamble",
    "KO": "Coca-Cola Co.",
    "PEP": "PepsiCo Inc.",
    "PM": "Philip Morris International",
    "EL": "Estee Lauder Companies",
    "CL": "Colgate-Palmolive",
    "GIS": "General Mills",
    "KHC": "Kraft Heinz Co.",
    # Media & Entertainment
    "NFLX": "Netflix Inc.",
    "DIS": "Walt Disney Co.",
    "CMCSA": "Comcast Corp.",
    "UBER": "Uber Technologies",
    "ABNB": "Airbnb Inc.",
    "SPOT": "Spotify Technology",
    "EA": "Electronic Arts",
    "TTWO": "Take-Two Interactive",
    # Fintech & Payments
    "V": "Visa Inc.",
    "MA": "Mastercard Inc.",
    "PYPL": "PayPal Holdings",
    "SQ": "Block Inc. (Square)",
    "FIS": "Fidelity National Info",
    "COIN": "Coinbase Global",
    # Financial Services
    "JPM": "JPMorgan Chase & Co.",
    "BAC": "Bank of America Corp.",
    "WFC": "Wells Fargo & Co.",
    "GS": "Goldman Sachs Group",
    "MS": "Morgan Stanley",
    "C": "Citigroup Inc.",
    "BLK": "BlackRock Inc.",
    "SCHW": "Charles Schwab Corp.",
    "AXP": "American Express Co.",
    "BRK-B": "Berkshire Hathaway",
    "USB": "U.S. Bancorp",
    "PNC": "PNC Financial Services",
    # Healthcare & Pharma
    "JNJ": "Johnson & Johnson",
    "UNH": "UnitedHealth Group",
    "LLY": "Eli Lilly & Co.",
    "ABBV": "AbbVie Inc.",
    "MRK": "Merck & Co.",
    "PFE": "Pfizer Inc.",
    "TMO": "Thermo Fisher Scientific",
    "ABT": "Abbott Laboratories",
    "AMGN": "Amgen Inc.",
    "GILD": "Gilead Sciences",
    "ISRG": "Intuitive Surgical",
    "MDT": "Medtronic plc",
    "BMY": "Bristol-Myers Squibb",
    "VRTX": "Vertex Pharmaceuticals",
    "REGN": "Regeneron Pharmaceuticals",
    # Industrials
    "BA": "Boeing Co.",
    "CAT": "Caterpillar Inc.",
    "GE": "GE Aerospace",
    "HON": "Honeywell International",
    "UPS": "United Parcel Service",
    "RTX": "RTX Corp. (Raytheon)",
    "DE": "Deere & Company",
    "LMT": "Lockheed Martin Corp.",
    "MMM": "3M Company",
    "FDX": "FedEx Corp.",
    # Energy
    "XOM": "Exxon Mobil Corp.",
    "CVX": "Chevron Corp.",
    "COP": "ConocoPhillips",
    "SLB": "Schlumberger Ltd.",
    "EOG": "EOG Resources",
    "PSX": "Phillips 66",
    # Utilities & Real Estate
    "NEE": "NextEra Energy",
    "DUK": "Duke Energy Corp.",
    "SO": "Southern Company",
    "AMT": "American Tower Corp.",
    "PLD": "Prologis Inc.",
    "CCI": "Crown Castle International",
    # Telecom
    "T": "AT&T Inc.",
    "VZ": "Verizon Communications",
    "TMUS": "T-Mobile US Inc.",
}
